### ISSUE TITLE
Adding multiple folders breaks the CSS on one

### ISSUE THREAD

**Issue by damacus** [JugglerX/hugo-whisper-theme#5]
Hey! 👋 

nice theme. I'm trying to build build . a site with docs and posts as the content. But I'm regularly getting one of them not rendering 

## Repro

```toml
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Minutes"
    url = "/minutes/"
    weight = 2

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3
```
